/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class uk_co_halfninja_videokit_Videokit */

#ifndef _Included_com_weezlabs_ffmpegkit_FFmpegKit
#define _Included_com_weezlabs_ffmpegkit_FFmpegKit
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     uk_co_halfninja_videokit_Videokit
 * Method:    run
 * Signature: ([Ljava/lang/String;)V
 */
JNIEXPORT jint JNICALL Java_com_weezlabs_ffmpegkit_FFmpegKit_run(JNIEnv *,
		jobject, jobjectArray);

JNIEXPORT jint JNICALL Java_com_weezlabs_ffmpegkit_FFmpegKit_runprotected(JNIEnv *,
		jobject, jobjectArray);

JNIEXPORT jstring JNICALL Java_com_weezlabs_ffmpegkit_FFmpegKit_getmetadataprotected(
		JNIEnv *, jobject, jobjectArray);

JNIEXPORT jint JNICALL Java_com_weezlabs_ffmpegkit_FFmpegKit_metadata(JNIEnv *,
		jobject, jobjectArray);

JNIEXPORT jstring JNICALL Java_com_weezlabs_ffmpegkit_FFmpegKit_getmetadata(
		JNIEnv *, jobject, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
